// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MoreBattleAnimations","status":true,"description":"Displays attack, skill, and item animations on the appropriate target's face or battler graphic in battle (v1.8.0).","parameters":{}}
];
