// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EnemyAttackAnimation","status":true,"description":"Displays enemy attack animations on player face graphics in battle.","parameters":{}}
];
